FROM node:latest

WORKDIR /usr/src/front_end/olduka
RUN curl -o- -L https://yarnpkg.com/install.sh | bash
COPY olduka/package*.json olduka/yarn.lock ./
RUN yarn install

WORKDIR /usr/src/front_end
COPY . ./

WORKDIR /usr/src/front_end/olduka