FROM node:latest AS build_stage
WORKDIR /usr/src/front_end/olduka
RUN curl -o- -L https://yarnpkg.com/install.sh | bash
COPY olduka/package*.json olduka/yarn.lock ./
RUN yarn install
WORKDIR /usr/src/front_end
COPY . ./
WORKDIR /usr/src/front_end/olduka
RUN npm run build

FROM node:alpine AS production_stage
COPY --from=build_stage /usr/src/front_end/olduka/dist /tmp/front_end
ENTRYPOINT ["cp", "-RT", "/tmp/front_end", "/usr/src/front_end"]