# Generated by Django 2.1.7 on 2019-03-11 22:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20190222_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='jwt_secret',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
