# Generated by Django 2.2.9 on 2020-02-24 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('OP', 'Open'), ('PA', 'Paid')], max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=20)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('receipt_number', models.CharField(max_length=15)),
                ('transaction_date', models.DateTimeField()),
                ('phone_number', models.CharField(max_length=15)),
                ('response_description', models.TextField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_payment', to='payment.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_item', to='product.Item')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='items',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='payment.InvoiceItem'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_invoice', to=settings.AUTH_USER_MODEL),
        ),
    ]
