# Generated by Django 2.2.10 on 2020-02-24 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesapayment',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='checkout_request_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='merchant_request_id',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='receipt_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='response_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='mpesapayment',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
