# Generated by Django 2.2.10 on 2020-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_auto_20200224_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='reminder_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
