# Generated by Django 2.2.10 on 2020-02-28 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_invoice_reminder_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='quantities_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
