# Generated by Django 2.2.3 on 2019-07-24 21:05

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields
import olduka.v1.product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('images', djongo.models.fields.ArrayModelField(model_container=olduka.v1.product.models.ProductImage)),
                ('price', djongo.models.fields.EmbeddedModelField(model_container=olduka.v1.product.models.Price, null=True)),
                ('category', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
    ]
