# Generated by Django 2.2.3 on 2019-10-09 23:27

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20191009_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.CASCADE, related_name='_cart_item', to='product.Item'),
        ),
    ]
