# Generated by Django 2.2.3 on 2019-10-10 12:59

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20191010_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='items',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cart.CartItem'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='product.Item'),
        ),
    ]
