# Generated by Django 2.2.3 on 2019-10-10 16:41

from django.db import migrations
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20191010_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=djongo.models.fields.ArrayReferenceField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart', to='cart.CartItem'),
        ),
    ]
