FROM python:3.6

ARG ENVIRONMENT_SETTINGS

WORKDIR /usr/src/api

COPY . ./

RUN pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install $(test "$ENVIRONMENT_SETTINGS" = PRODUCTION || echo "--dev") --deploy --system --ignore-pipfile