FROM python:3.6

WORKDIR /usr/src/api

COPY . ./

RUN pip install --upgrade pip
RUN pip install pipenv
RUN pipenv install --deploy --system --ignore-pipfile

RUN useradd -ms /bin/bash celery
USER celery